import { Inter } from 'next/font/google'
import { Header } from './components/shared/Header';
import { Footer } from './components/shared/Footer';
import 'app/sass/globals.sass';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Future World',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header />
      <body className={inter.className}>
        {children}
      </body>
      <Footer/>
    </html>
  )
}
